name: Build

on: 
    workflow_dispatch:

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build binary 4k broken
      run: |
        docker build -t evwii_builder .
        docker run --rm -v ${PWD}:/project evwii_builder make
    - uses: actions/upload-artifact@v3
      with:
       name: evwii
       path: "*.wps"
